// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MantisNetMvc.Infrastructure.Data;

#nullable disable

namespace MantisNetMvc.Infrastructure.Migrations;

[DbContext(typeof(MantisDbContext))]
public class MantisDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
#pragma warning restore 612, 618
    }
}
